services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: userenclair!cestpasbien
      POSTGRES_PASSWORD: motdepasseenclair!cestpasbien
      POSTGRES_DB: express_dev_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network

  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - backend-network

volumes:
  postgres-data:

networks:
  backend-network:
